# calls that error

    Code
      synchronise(afun())
    Condition
      Error:
      ! in callr subprocess.
      Caused by error:
      ! nope

